sudo: false

addons:
  apt_packages:
    - lib32stdc++6

env:
  - SOURCEMOD=1.7.0

before_script:
  - FILE="sourcemod-$SOURCEMOD-linux.tar.gz"
  - wget http://www.gsptalk.com/mirror/sourcemod/$FILE
  - tar -xzf $FILE
  - chmod +rx addons/sourcemod/scripting/spcomp
  - cd addons/sourcemod/scripting/
  
script:
  - ./spcomp multicolors_example.sp

notifications:
  email: 
    recipients:
      - webmaster@bara.in
    on_success: always
    on_failure: always
