language: bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib lynx

before_script:
  - curl -L https://raw.githubusercontent.com/Bara20/SM_Hosties2/master/sourcemod.sh | bash
  - chmod +rx addons/sourcemod/scripting/spcomp
  - chmod +rx addons/sourcemod/scripting/compile.sh
  - cd addons/sourcemod/scripting/
  
script:
  - ./spcomp multicolors_example.sp
