language: cpp
compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib

install:
  - wget http://www.sourcemod.net/smdrop/1.6/sourcemod-1.6.2-git4560-linux.tar.gz -O /tmp/sourcemod.tar.gz
  - tar -xzvf /tmp/sourcemod.tar.gz

before_script:
  - chmod +rx addons/sourcemod/scripting/spcomp
  - chmod +rx addons/sourcemod/scripting/compile.sh
  - cd addons/sourcemod/scripting/
  
script:
  - ./spcomp multicolors_example.sp